camunda:
  bpm:
    admin-user:
      id: CamundaAdmin
      password: CamundaAdmin
      firstName: Camunda
      lastName: Admin
      email: CamundaAdmin@camunda.com
#    enableExceptionsAfterUnhandledBpmnError: true
    filter:
      create: All tasks
    generic-properties:
      properties:
        javaSerializationFormatEnabled: true
        # History Cleanup
#        historyCleanupStrategy: removalTimeBased
#        historyRemovalTimeStrategy: end
#        historyTimeToLive: 30
#        batchOperationHistoryTimeToLive: 1
#        historyCleanupJobLogTimeToLive: 1
#        historyCleanupBatchWindowStartTime: "00:00"
#        historyCleanupBatchWindowEndTime: "10:00"
#        saturdayHistoryCleanupBatchWindowStartTime: "21:00"
#        saturdayHistoryCleanupBatchWindowEndTime: "02:00"
#        sundayHistoryCleanupBatchWindowStartTime: "21:00"
#        sundayHistoryCleanupBatchWindowEndTime: "02:00"
        # Java Serialization - enable at risk!
#        javaSerializationFormatEnabled: true
        # MDC Logging
#        loggingContextActivityId: activityName
        # Tasklist Query
#        queryMaxResultsLimit: 2000
        # Telemetry
        initializeTelemetry: false
        telemetryReporterActivate: false
#    job-execution:
#     enabled: false
spring:
  h2.console.enabled: true
  datasource:
    #    url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:camunda-db
    username: sa
    password: sa

# Logging Settings
logging:
  file:
    path: ./logs           # specify a path to write to file, otherwise it defaults to the console.
  level:
    # Camunda Loggers
    org.camunda: INFO     # WARNING!! THIS NAMESPACE WILL OUTPUT ALL CAMUNDA LOGS AT THE SPECIFIED LEVEL.
    org.camunda.bpm.spring.boot.spin1: DEBUG
#    org.camunda.bpm.engine.cmd: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity: DEBUG
#    org.camunda.bpm.engine.impl.batch.BatchEntity: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity.ExecutionEntity: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity.IncidentEntity: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity.JobEntity: DEBUG
#    org.camunda.bpm.engine.impl.persistence.entity.VariableInstanceEntity: DEBUG
#    org.camunda.bpm.engine.jobexecutor: DEBUG
#    org.camunda.bpm.engine.persistence: DEBUG
#    org.camunda.bpm.engine.tx: DEBUG
#    # Common Camunda Dependencies
#    org.apache.ibatis: INFO
#    # Add Catalina logging
#    org.apache.catalina: INFO
#    # Add Tomcat logging
#    org.apache.tomcat: INFO